"""Auto-generated type stubs for @configurable decorators.

This file is automatically generated by scripts/generate_stubs.py.
Do not edit manually - changes will be overwritten.
"""

from collections.abc import Callable
from typing import override

from hipr import MakeableModel
import pandas as pd
from pdval import Finite, Validated

class bollinger_bands:  # noqa: N801
  class Config(MakeableModel[Callable[[Validated[pd.Series, Finite]], pd.DataFrame]]):
    window: int
    num_std: float
    def __init__(self, *, window: int = 20, num_std: float = 2.0) -> None: ...
    @override
    def make(self) -> Callable[[Validated[pd.Series, Finite]], pd.DataFrame]: ...

  window: int
  num_std: float
  def __new__(
    cls, data: Validated[pd.Series, Finite], *, window: int = 20, num_std: float = 2.0
  ) -> pd.DataFrame: ...
  @classmethod
  def to_config(cls) -> Config: ...
