"""Auto-generated type stubs for @configurable decorators.

This file is automatically generated by scripts/generate_stubs.py.
Do not edit manually - changes will be overwritten.
"""

from typing import override

from hipr import MakeableModel
import pandas as pd
from pdval import Finite, Validated

class bollinger_bands:  # noqa: N801
  class Config(MakeableModel["bollinger_bands"]):
    window: int
    num_std: float
    def __init__(self, *, window: int = 20, num_std: float = 2.0) -> None: ...
    @override
    def make(self) -> bollinger_bands: ...

  window: int
  num_std: float
  type Type = "bollinger_bands"
  def __new__(
    cls, data: Validated[pd.Series, Finite], *, window: int = 20, num_std: float = 2.0
  ) -> pd.DataFrame: ...
  def __call__(
    self, data: Validated[pd.Series, Finite], *, window: int = 20, num_std: float = 2.0
  ) -> pd.DataFrame: ...
