"""Auto-generated type stubs for @configurable decorators.

This file is automatically generated by scripts/generate_stubs.py.
Do not edit manually - changes will be overwritten.
"""

from collections.abc import Callable
from typing import Literal, override

from hipr import MakeableModel
import pandas as pd
from pdval import Ge as ColsGe, HasColumns, NonNegative, Validated

class churn_factor:  # noqa: N801
  class Config(
    MakeableModel[
      Callable[
        [
          Validated[
            pd.DataFrame,
            HasColumns[Literal["high", "low", "volume"]],
            ColsGe[Literal["high", "low"]],
            NonNegative,
          ],
          str,
          float | None,
        ],
        pd.DataFrame,
      ]
    ]
  ):
    epsilon: float
    def __init__(self, *, epsilon: float = 1e-09) -> None: ...
    @override
    def make(
      self,
    ) -> Callable[
      [
        Validated[
          pd.DataFrame,
          HasColumns[Literal["high", "low", "volume"]],
          ColsGe[Literal["high", "low"]],
          NonNegative,
        ],
        str,
        float | None,
      ],
      pd.DataFrame,
    ]: ...

  epsilon: float
  def __new__(
    cls,
    data: Validated[
      pd.DataFrame,
      HasColumns[Literal["high", "low", "volume"]],
      ColsGe[Literal["high", "low"]],
      NonNegative,
    ],
    *,
    epsilon: float = 1e-09,
    fill_strategy: str = "zero",
    fill_value: float | None = None,
  ) -> pd.DataFrame: ...
  @classmethod
  def to_config(cls) -> Config: ...
