"""Auto-generated type stubs for @configurable decorators.

This file is automatically generated by scripts/generate_stubs.py.
Do not edit manually - changes will be overwritten.
"""

from typing import override

from hipr import MakeableModel
import pandas as pd
from pdval import Finite, Validated

class macd:  # noqa: N801
  class Config(MakeableModel["macd"]):
    fast_period: int
    slow_period: int
    signal_period: int
    def __init__(
      self, *, fast_period: int = 12, slow_period: int = 26, signal_period: int = 9
    ) -> None: ...
    @override
    def make(self) -> macd: ...

  fast_period: int
  slow_period: int
  signal_period: int
  type Type = "macd"
  def __new__(
    cls,
    data: Validated[pd.Series, Finite],
    *,
    fast_period: int = 12,
    slow_period: int = 26,
    signal_period: int = 9,
  ) -> pd.DataFrame: ...
  def __call__(
    self,
    data: Validated[pd.Series, Finite],
    *,
    fast_period: int = 12,
    slow_period: int = 26,
    signal_period: int = 9,
  ) -> pd.DataFrame: ...
