"""Auto-generated type stubs for @configurable decorators.

This file is automatically generated by scripts/generate_stubs.py.
Do not edit manually - changes will be overwritten.
"""

from collections.abc import Callable
from typing import Literal, override

from hipr import MakeableModel
import pandas as pd
from pdval import Ge as GeValidator, HasColumns, Validated

class mfi:  # noqa: N801
  class Config(
    MakeableModel[
      Callable[
        [
          Validated[
            pd.DataFrame,
            HasColumns[Literal["high", "low", "close", "volume"]],
            GeValidator[Literal["high", "low"]],
          ]
        ],
        pd.DataFrame,
      ]
    ]
  ):
    window: int
    epsilon: float
    def __init__(self, *, window: int = 14, epsilon: float = 1e-09) -> None: ...
    @override
    def make(
      self,
    ) -> Callable[
      [
        Validated[
          pd.DataFrame,
          HasColumns[Literal["high", "low", "close", "volume"]],
          GeValidator[Literal["high", "low"]],
        ]
      ],
      pd.DataFrame,
    ]: ...

  window: int
  epsilon: float
  def __new__(
    cls,
    data: Validated[
      pd.DataFrame,
      HasColumns[Literal["high", "low", "close", "volume"]],
      GeValidator[Literal["high", "low"]],
    ],
    *,
    window: int = 14,
    epsilon: float = 1e-09,
  ) -> pd.DataFrame: ...
  @classmethod
  def to_config(cls) -> Config: ...
