"""Auto-generated type stubs for @configurable decorators.

This file is automatically generated by scripts/generate_stubs.py.
Do not edit manually - changes will be overwritten.
"""

from collections.abc import Callable
from typing import Literal, override

from hipr import MakeableModel
import pandas as pd
from pdval import HasColumns, Validated

class obv:  # noqa: N801
  class Config(
    MakeableModel[
      Callable[
        [Validated[pd.DataFrame, HasColumns[Literal["close", "volume"]]]], pd.DataFrame
      ]
    ]
  ):
    @override
    def make(
      self,
    ) -> Callable[
      [Validated[pd.DataFrame, HasColumns[Literal["close", "volume"]]]], pd.DataFrame
    ]: ...

  def __new__(
    cls, data: Validated[pd.DataFrame, HasColumns[Literal["close", "volume"]]]
  ) -> pd.DataFrame: ...
  @classmethod
  def to_config(cls) -> Config: ...
