"""Auto-generated type stubs for @configurable decorators.

This file is automatically generated by scripts/generate_stubs.py.
Do not edit manually - changes will be overwritten.
"""

from typing import Literal, override

from hipr import MakeableModel
import pandas as pd
from pdval import HasColumns, Validated

class obv:  # noqa: N801
  class Config(MakeableModel["obv"]):
    @override
    def make(self) -> obv: ...

  type Type = "obv"
  def __new__(
    cls, data: Validated[pd.DataFrame, HasColumns[Literal["close", "volume"]]]
  ) -> pd.DataFrame: ...
  def __call__(
    self, data: Validated[pd.DataFrame, HasColumns[Literal["close", "volume"]]]
  ) -> pd.DataFrame: ...
