"""Auto-generated type stubs for @configurable decorators.

This file is automatically generated by scripts/generate_stubs.py.
Do not edit manually - changes will be overwritten.
"""

from typing import Literal

from hipr.config import MakeableModel
import pandas as pd
from pdval import HasColumns, Validated

class ObvConfig(MakeableModel[pd.DataFrame]):
  pass

class _ObvConfigurable:
  Config: type[ObvConfig]
  def __call__(
    self, data: Validated[pd.DataFrame, HasColumns[Literal["close", "volume"]]]
  ) -> pd.DataFrame: ...

type obv = _ObvConfigurable
