"""Auto-generated type stubs for @configurable decorators.

This file is automatically generated by scripts/generate_stubs.py.
Do not edit manually - changes will be overwritten.
"""

from collections.abc import Callable
from typing import Literal, override

from hipr import MakeableModel
import pandas as pd
from pdval import Datetime, Ge as GeValidator, HasColumns, Index, Validated

class opening_range:  # noqa: N801
  class Config(
    MakeableModel[
      Callable[
        [
          Validated[
            pd.DataFrame,
            HasColumns[Literal["high", "low", "close"]],
            Index[Datetime],
            GeValidator[Literal["high", "low"]],
          ],
          str,
        ],
        pd.DataFrame,
      ]
    ]
  ):
    minutes: int
    def __init__(self, *, minutes: int = 30) -> None: ...
    @override
    def make(
      self,
    ) -> Callable[
      [
        Validated[
          pd.DataFrame,
          HasColumns[Literal["high", "low", "close"]],
          Index[Datetime],
          GeValidator[Literal["high", "low"]],
        ],
        str,
      ],
      pd.DataFrame,
    ]: ...

  minutes: int
  def __new__(
    cls,
    data: Validated[
      pd.DataFrame,
      HasColumns[Literal["high", "low", "close"]],
      Index[Datetime],
      GeValidator[Literal["high", "low"]],
    ],
    *,
    minutes: int = 30,
    session_start: str = "09:30",
  ) -> pd.DataFrame: ...
  @classmethod
  def to_config(cls) -> Config: ...
