"""Auto-generated type stubs for @configurable decorators.

This file is automatically generated by scripts/generate_stubs.py.
Do not edit manually - changes will be overwritten.
"""

from collections.abc import Callable
from typing import Literal, override

from hipr import MakeableModel
import pandas as pd
from pdval import Datetime, Ge as GeValidator, HasColumns, Index, Validated

class pivot_points:  # noqa: N801
  class Config(
    MakeableModel[
      Callable[
        [
          Validated[
            pd.DataFrame,
            HasColumns[Literal["high", "low", "close"]],
            Index[Datetime],
            GeValidator[Literal["high", "low"]],
          ],
          Literal["standard", "fibonacci", "woodie", "camarilla"],
          Literal["D", "W", "ME"],
        ],
        pd.DataFrame,
      ]
    ]
  ):
    @override
    def make(
      self,
    ) -> Callable[
      [
        Validated[
          pd.DataFrame,
          HasColumns[Literal["high", "low", "close"]],
          Index[Datetime],
          GeValidator[Literal["high", "low"]],
        ],
        Literal["standard", "fibonacci", "woodie", "camarilla"],
        Literal["D", "W", "ME"],
      ],
      pd.DataFrame,
    ]: ...

  def __new__(
    cls,
    data: Validated[
      pd.DataFrame,
      HasColumns[Literal["high", "low", "close"]],
      Index[Datetime],
      GeValidator[Literal["high", "low"]],
    ],
    method: Literal["standard", "fibonacci", "woodie", "camarilla"] = "standard",
    period: Literal["D", "W", "ME"] = "D",
  ) -> pd.DataFrame: ...
  @classmethod
  def to_config(cls) -> Config: ...
