"""Auto-generated type stubs for @configurable decorators.

This file is automatically generated by scripts/generate_stubs.py.
Do not edit manually - changes will be overwritten.
"""

from typing import Literal, override

from hipr import MakeableModel
import pandas as pd
from pdval import Datetime, Ge as GeValidator, HasColumns, Index, Validated

class pivot_points:  # noqa: N801
  class Config(MakeableModel["pivot_points"]):
    @override
    def make(self) -> pivot_points: ...

  type Type = "pivot_points"
  def __new__(
    cls,
    data: Validated[
      pd.DataFrame,
      HasColumns[Literal["high", "low", "close"]],
      Index[Datetime],
      GeValidator[Literal["high", "low"]],
    ],
    method: Literal["standard", "fibonacci", "woodie", "camarilla"] = "standard",
    period: Literal["D", "W", "ME"] = "D",
  ) -> pd.DataFrame: ...
  def __call__(
    self,
    data: Validated[
      pd.DataFrame,
      HasColumns[Literal["high", "low", "close"]],
      Index[Datetime],
      GeValidator[Literal["high", "low"]],
    ],
    method: Literal["standard", "fibonacci", "woodie", "camarilla"] = "standard",
    period: Literal["D", "W", "ME"] = "D",
  ) -> pd.DataFrame: ...
