"""Auto-generated type stubs for @configurable decorators.

This file is automatically generated by scripts/generate_stubs.py.
Do not edit manually - changes will be overwritten.
"""

from typing import override

from hipr import MakeableModel
import pandas as pd
from pdval import Finite, Validated

class rsi:  # noqa: N801
  class Config(MakeableModel["rsi"]):
    window: int
    epsilon: float
    def __init__(self, *, window: int = 14, epsilon: float = 1e-09) -> None: ...
    @override
    def make(self) -> rsi: ...

  window: int
  epsilon: float
  type Type = "rsi"
  def __new__(
    cls, data: Validated[pd.Series, Finite], *, window: int = 14, epsilon: float = 1e-09
  ) -> pd.Series: ...
  def __call__(
    self,
    data: Validated[pd.Series, Finite],
    *,
    window: int = 14,
    epsilon: float = 1e-09,
  ) -> pd.Series: ...
