"""Auto-generated type stubs for @configurable decorators.

This file is automatically generated by scripts/generate_stubs.py.
Do not edit manually - changes will be overwritten.
"""

from hipr.config import MakeableModel
import pandas as pd
from pdval import Finite, NonEmpty, Validated

class RsiConfig(MakeableModel[pd.Series]):
    window: int
    epsilon: float
    def __init__(self, *, window: int = 14, epsilon: float = 1e-09) -> None: ...

class _RsiConfigurable:
    Config: type[RsiConfig]
    def __call__(
        self,
        data: Validated[pd.Series, Finite, NonEmpty],
        *,
        window: int = 14,
        epsilon: float = 1e-09,
    ) -> pd.Series: ...

type rsi = _RsiConfigurable
