"""Auto-generated type stubs for @configurable decorators.

This file is automatically generated by scripts/generate_stubs.py.
Do not edit manually - changes will be overwritten.
"""

from hipr.config import MakeableModel
import pandas as pd
from pdval import Datetime, Index, NonNegative, Validated

# Module constants
_DEFAULT_MIN_SAMPLES = 3

class RvolConfig(MakeableModel[pd.Series]):
  window: int
  epsilon: float
  def __init__(self, *, window: int = 20, epsilon: float = 1e-09) -> None: ...

class RvolIntradayConfig(MakeableModel[pd.Series]):
  min_samples: int
  epsilon: float
  def __init__(
    self, *, min_samples: int = _DEFAULT_MIN_SAMPLES, epsilon: float = 1e-09
  ) -> None: ...

class _RvolConfigurable:
  Config: type[RvolConfig]
  def __call__(
    self,
    data: Validated[pd.Series, NonNegative],
    *,
    window: int = 20,
    epsilon: float = 1e-09,
  ) -> pd.Series: ...

type rvol = _RvolConfigurable

class _RvolIntradayConfigurable:
  Config: type[RvolIntradayConfig]
  def __call__(
    self,
    data: Validated[pd.Series, NonNegative, Index[Datetime]],
    *,
    lookback_days: int | None = None,
    min_samples: int = _DEFAULT_MIN_SAMPLES,
    epsilon: float = 1e-09,
  ) -> pd.Series: ...

type rvol_intraday = _RvolIntradayConfigurable
