"""Auto-generated type stubs for @configurable decorators.

This file is automatically generated by scripts/generate_stubs.py.
Do not edit manually - changes will be overwritten.
"""

from collections.abc import Callable
from typing import override

from hipr import MakeableModel
import pandas as pd
from pdval import Finite, Validated

class sector_correlation:  # noqa: N801
  class Config(
    MakeableModel[
      Callable[
        [Validated[pd.Series, Finite], Validated[pd.Series, Finite] | None], pd.Series
      ]
    ]
  ):
    @override
    def make(
      self,
    ) -> Callable[
      [Validated[pd.Series, Finite], Validated[pd.Series, Finite] | None], pd.Series
    ]: ...

  def __new__(
    cls,
    stock_data: Validated[pd.Series, Finite],
    sector_data: Validated[pd.Series, Finite] | None = None,
  ) -> pd.Series: ...
  @classmethod
  def to_config(cls) -> Config: ...
