"""Auto-generated type stubs for @configurable decorators.

This file is automatically generated by scripts/generate_stubs.py.
Do not edit manually - changes will be overwritten.
"""

from hipr.config import MakeableModel
import pandas as pd
from pdval import Finite, Validated

class SectorCorrelationConfig(MakeableModel[pd.Series]):
  pass

class _SectorCorrelationConfigurable:
  Config: type[SectorCorrelationConfig]
  def __call__(
    self,
    stock_data: Validated[pd.Series, Finite],
    sector_data: Validated[pd.Series, Finite] | None = None,
  ) -> pd.Series: ...

type sector_correlation = _SectorCorrelationConfigurable
