"""Auto-generated type stubs for @configurable decorators.

This file is automatically generated by scripts/generate_stubs.py.
Do not edit manually - changes will be overwritten.
"""

from typing import override

from hipr import MakeableModel
import pandas as pd
from pdval import Finite, Validated

class sector_correlation:  # noqa: N801
  class Config(MakeableModel["sector_correlation"]):
    @override
    def make(self) -> sector_correlation: ...

  type Type = "sector_correlation"
  def __new__(
    cls,
    stock_data: Validated[pd.Series, Finite],
    sector_data: Validated[pd.Series, Finite] | None = None,
  ) -> pd.Series: ...
  def __call__(
    self,
    stock_data: Validated[pd.Series, Finite],
    sector_data: Validated[pd.Series, Finite] | None = None,
  ) -> pd.Series: ...
