"""Auto-generated type stubs for @configurable decorators.

This file is automatically generated by scripts/generate_stubs.py.
Do not edit manually - changes will be overwritten.
"""

from collections.abc import Callable
from typing import override

from hipr import MakeableModel
import pandas as pd
from pdval import Finite, Validated

class slope:  # noqa: N801
  class Config(MakeableModel[Callable[[Validated[pd.Series, Finite]], pd.Series]]):
    window: int
    def __init__(self, *, window: int = 20) -> None: ...
    @override
    def make(self) -> Callable[[Validated[pd.Series, Finite]], pd.Series]: ...

  window: int
  def __new__(
    cls, data: Validated[pd.Series, Finite], *, window: int = 20
  ) -> pd.Series: ...
  @classmethod
  def to_config(cls) -> Config: ...
