"""Auto-generated type stubs for @configurable decorators.

This file is automatically generated by scripts/generate_stubs.py.
Do not edit manually - changes will be overwritten.
"""

from typing import override

from hipr import MakeableModel
import pandas as pd
from pdval import Finite, Validated

class slope:  # noqa: N801
  class Config(MakeableModel["slope"]):
    window: int
    def __init__(self, *, window: int = 20) -> None: ...
    @override
    def make(self) -> slope: ...

  window: int
  type Type = "slope"
  def __new__(
    cls, data: Validated[pd.Series, Finite], *, window: int = 20
  ) -> pd.Series: ...
  def __call__(
    self, data: Validated[pd.Series, Finite], *, window: int = 20
  ) -> pd.Series: ...
