"""Auto-generated type stubs for @configurable decorators.

This file is automatically generated by scripts/generate_stubs.py.
Do not edit manually - changes will be overwritten.
"""

from hipr.config import MakeableModel
import pandas as pd
from pdval import Finite, NonEmpty, NonNaN, Validated

class SlopeConfig(MakeableModel[pd.Series]):
    window: int
    def __init__(self, *, window: int = 20) -> None: ...

class _SlopeConfigurable:
    Config: type[SlopeConfig]
    def __call__(
        self, data: Validated[pd.Series, Finite, NonNaN, NonEmpty], *, window: int = 20
    ) -> pd.Series: ...

type slope = _SlopeConfigurable
