"""Auto-generated type stubs for @configurable decorators.

This file is automatically generated by scripts/generate_stubs.py.
Do not edit manually - changes will be overwritten.
"""

from typing import override

from hipr import MakeableModel
import pandas as pd
from pdval import Datetime, Finite, Index, Validated

# Module constants
_DEFAULT_MIN_SAMPLES = 3

class zscore:  # noqa: N801
  class Config(MakeableModel["zscore"]):
    window: int
    epsilon: float
    def __init__(self, *, window: int = 20, epsilon: float = 1e-09) -> None: ...
    @override
    def make(self) -> zscore: ...

  window: int
  epsilon: float
  type Type = "zscore"
  def __new__(
    cls, data: Validated[pd.Series, Finite], *, window: int = 20, epsilon: float = 1e-09
  ) -> pd.Series: ...
  def __call__(
    self,
    data: Validated[pd.Series, Finite],
    *,
    window: int = 20,
    epsilon: float = 1e-09,
  ) -> pd.Series: ...

class zscore_intraday:  # noqa: N801
  class Config(MakeableModel["zscore_intraday"]):
    min_samples: int
    epsilon: float
    def __init__(
      self, *, min_samples: int = _DEFAULT_MIN_SAMPLES, epsilon: float = 1e-09
    ) -> None: ...
    @override
    def make(self) -> zscore_intraday: ...

  min_samples: int
  epsilon: float
  type Type = "zscore_intraday"
  def __new__(
    cls,
    data: Validated[pd.Series, Index[Datetime]],
    *,
    lookback_days: int | None = None,
    min_samples: int = _DEFAULT_MIN_SAMPLES,
    epsilon: float = 1e-09,
  ) -> pd.Series: ...
  def __call__(
    self,
    data: Validated[pd.Series, Index[Datetime]],
    *,
    lookback_days: int | None = None,
    min_samples: int = _DEFAULT_MIN_SAMPLES,
    epsilon: float = 1e-09,
  ) -> pd.Series: ...
