"""Auto-generated type stubs for @configurable decorators.

This file is automatically generated by scripts/generate_stubs.py.
Do not edit manually - changes will be overwritten.
"""

from collections.abc import Callable
from typing import override

from hipr import MakeableModel
import pandas as pd
from pdval import Datetime, Finite, Index, Validated

# Module constants
_DEFAULT_MIN_SAMPLES = 3

class zscore:  # noqa: N801
  class Config(MakeableModel[Callable[[Validated[pd.Series, Finite]], pd.Series]]):
    window: int
    epsilon: float
    def __init__(self, *, window: int = 20, epsilon: float = 1e-09) -> None: ...
    @override
    def make(self) -> Callable[[Validated[pd.Series, Finite]], pd.Series]: ...

  window: int
  epsilon: float
  def __new__(
    cls, data: Validated[pd.Series, Finite], *, window: int = 20, epsilon: float = 1e-09
  ) -> pd.Series: ...
  @classmethod
  def to_config(cls) -> Config: ...

class zscore_intraday:  # noqa: N801
  class Config(
    MakeableModel[
      Callable[[Validated[pd.Series, Index[Datetime]], int | None], pd.Series]
    ]
  ):
    min_samples: int
    epsilon: float
    def __init__(
      self, *, min_samples: int = _DEFAULT_MIN_SAMPLES, epsilon: float = 1e-09
    ) -> None: ...
    @override
    def make(
      self,
    ) -> Callable[[Validated[pd.Series, Index[Datetime]], int | None], pd.Series]: ...

  min_samples: int
  epsilon: float
  def __new__(
    cls,
    data: Validated[pd.Series, Index[Datetime]],
    *,
    lookback_days: int | None = None,
    min_samples: int = _DEFAULT_MIN_SAMPLES,
    epsilon: float = 1e-09,
  ) -> pd.Series: ...
  @classmethod
  def to_config(cls) -> Config: ...
